### PR TITLE
'exclude' option for triggers, 'receive' event

### PR DESCRIPTION
**Pull request by Yahav**
This pull request adds:
- a 'received' event after the response has been received and before the DOM changes has been made.
- the "defaultTrigger" property can either be a boolean or an object:
```
{
  enable: boolean,
  exclude: string[], // an array of selectors to exclude as a trigger, for example: a[data-pjax-disable]
}
```
- the "scripts" property can either be a string of selectors as it currently is or an object:
```
{
  forceLoad: string, // same functionality as the original script property
  exclude: string[], // an array of script selectors to exclude from execution even if its new, for example: script[data-pjax-disable]
}
```

## How Has This Been Tested?
Wasn't tested

## Types of changes
- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactor (no bug fix and new feature but improvements)

## Checklist:
- [x] My change requires new tests.
- [ ] I have added tests to cover my changes.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by PaperStrike** [comment]
Thanks. But there is a question I have.

Why would we need the `scripts.exclude`? Is there really a modern site that puts some scripts in a switch container, and didn't expect these scripts to be executed during the switches?

There's a blog theme I involved in and you can see it in my GitHub organization. There were some scripts in the theme that were not supposed to be executed during the switches, but they were placed in some switching parts. I know what it is like. Now they are gone, because if these scripts are meant to be executed only once, then developers shouldn't put them in the switching parts, it's a waste of performance, and if he makes use of the `X-Pjax-Selectors` headers, it's a waste of bandwidth, too. So in my view, the need to filter out some scripts from the switching part in Pjax side is weird, and I don't expect to maintain code that is made for weird needs. 🤔

And with the [hooks](https://github.com/PaperStrike/Pjax/pull/177) avaliable, it will be possible to filter out the unwanted scripts before the document is processed by Pjax, as an interim solution when one migrating to a compliant HTML structure.

What do you think?

**Comment by PaperStrike** [comment]
Also, without the hooks, scripts can be filtered out with [switch callbacks](https://github.com/PaperStrike/Pjax/tree/v2.1.0#switches).

**Comment by PaperStrike** [comment]
Ah, the question still applies. I may write the docs like "this may get removed at any time especially if a new feature conflicts with it" since I can't figure out a good use case for it.

Array `exclude` is replaced with a single string. the [`selectors`](https://github.com/PaperStrike/Pjax/tree/v2.1.0#selectors) option takes an array for the [`switches`](https://github.com/PaperStrike/Pjax/tree/v2.1.0#switches) option. We don't have to do the same for `exclude`. Just [join the selectors with commas (`,`)](https://developer.mozilla.org/en-US/docs/Web/CSS/Selector_list).

Thank you. Any suggestions?

**Comment by Yahav** [comment]
You can take it out if it bothers you that much. i just don't get why, imho a package should be as customizable/elastic as possible to match as much use cases as long as it remains lightweight, those kind of features won't do much.

**Comment by PaperStrike** [comment]
@Yahav Here's a detailed explanation:

1. Selecting a script in the `exclude` option doesn't mean the script won't be switched. The event listeners, the correct references on and of the original script element in the document will be lost, just like all the switching elements. If you don't like a script element to be switched, turn to use more specific CSS selectors in the `selectors` option or use a custom switch callback.
2. It is not a guarantee of running the script exactly once. If the script is wrapped in a switching container (let's say in page A), and sometimes the container will not contain the script (let's say in page B), then when a user started to read the site from page B, the script will not be executed at all even after the user navigates to page A. Letting a page to affect other pages' browsing experience seems quite weird and almost always bug-causing. If you need your script to run exactly once, please put it outside of the switching elements.
3. Pjax aims to simulate initial page loads when switching pages, and the initial page load executes all the script elements.

I do agree with you that the plugin should be customizable as long as it remains light weight to support more use cases, but I really don't think there's a valid use case for this. In my first comment, I mentioned the removal of some such scripts in the blog theme, and now I can tell you that the removal is exactly a fix for the bug in the reason 2.

I wish we can have more agreement on this.

**Comment by PaperStrike** [comment]
@Yahav Thank you for this PR!

**Pull request merged**
